### ISSUE TITLE
Could you please make an new release?

### ISSUE THREAD

**Issue by subwaystation** [marschall-lab/panacus#12]
In order to use the new file format feature in pipeline development, we need a new release, because we can only work with a Conda package...... 
Would you please provide a new one @danydoerr ?

Thanks!

**Comment by danydoerr** [comment]
done

**Comment by danydoerr** [comment]
@subwaystation it's already merged into bioconda https://github.com/bioconda/bioconda-recipes/pull/43785

**Comment by subwaystation** [comment]
:+1: 
Thanks!!
