### ISSUE TITLE
How to Visualize the results of the minigraph-cactus?

### ISSUE THREAD

**Issue by ld9866** [marschall-lab/panacus#14]
Dear developer:
Now we have found a problem, according to the example you provided, we can not extract the results of MC for visual analysis, including https://github.com/marschall-lab/panacus/issues/4.
Our problem is that the path file obtained in the first step is empty, but we can extract the path file after using vg to convert to version 1.0, I would like to ask why?
code:
grep '^P' test.full.gfa | cut -f2 > test.paths.txt

**Comment by ld9866** [comment]
Besides, we found the example file "hprc-v1.0-mc-grch38.gfa" is also the version gfa1.0. could you give me a example to visualize the MC result with version gfa 1.1?

**Comment by ld9866** [comment]
l found the first line of "hprc-v1.0-mc-grch38.gfa" is H       VN:Z:1.0, but our MC result is H       VN:Z:1.1        RS:Z:Reference1.
I don't know if that's the reason for the problem

**Comment by danydoerr** [comment]
The difference between v1.0 and v1.1 is that the latter also supports W-lines. However, panacus does not alter its behavior depending on different GFA versions. So, no, the GFA header line does not matter. In fact, panacus will still process GFA files even if they do not contain that header line. 

> Our problem is that the path file obtained in the first step is empty, but we can extract the path file after using vg to convert to version 1.0, I would like to ask why?

If the original GFA file is v1.1, I'd guess paths are encoded in W-lines:
```shell
grep -e '^W' hprc-v1.0-mc-grch38.gfa | cut -f2-6 | awk '{ print $1 "#" $2 "#" $3 ":" $4 "-" $5 }' >> hprc-v1.0-mc-grch38.paths.txt
```
> Now we have found a problem, according to the example you provided, we can not extract the results of MC for visual analysis, including #4.

The description in #4 for hprc-v1.0-mc-grch38.gfa is obsolete, because panacus now provides shortcuts for grouping (`-H`, '-S'), so you do not need to do that by hand. The following code replaces all of #4:

```shell

grep -ive 'grch38\|chm13' hprc-v1.0-mc-grch38.paths.txt > hprc-v1.0-mc-grch38.paths.haplotypes.txt

RUST_LOG=info panacus histgrowth -t16 -q 0,1,0.5,0.1 -S -s hprc-v1.0-mc-grch38.paths.haplotypes.txt hprc-v1.0-mc-grch38.gfa > hprc-v1.0-mc-grch38.histgrowth.node.txt

panacus-visualize hprc-v1.0-mc-grch38.histgrowth.node.txt >  hprc-v1.0-mc-grch38.histgrowth.node.pdf
```

... and to produce a plot quantifying the non-reference sequence of the graph:

```shell

grep -ie 'grch38' hprc-v1.0-mc-grch38.paths.txt > hprc-v1.0-mc-grch38.paths.grch38.txt

RUST_LOG=info panacus histgrowth -t16 -c bp -q 0,1,0.5,0.1 -e hprc-v1.0-mc-grch38.paths.grch38.txt -S -s hprc-v1.0-mc-grch38.paths.haplotypes.txt hprc-v1.0-mc-grch38.gfa > hprc-v1.0-mc-grch38.histgrowth.nogrch38.bp.txt

panacus-visualize hprc-v1.0-mc-grch38.histgrowth.nogrch38.bp.txt >  hprc-v1.0-mc-grch38.histgrowth.nogrch38.bp.pdf
```

**Comment by ld9866** [comment]
Hello! 
Since we deleted the result file by mistake because it was an empty file, we ran a new file, and I uploaded our pan-genomic result file of 27 genomes corresponding to your requirements, which is ok. However, we found that the result was not rational.

[pig.full.histgrowth.ref.bp.txt](https://github.com/marschall-lab/panacus/files/13543678/pig.full.histgrowth.ref.bp.txt)
[pig.full.histgrowth.noref.bp.pdf](https://github.com/marschall-lab/panacus/files/13543813/pig.full.histgrowth.noref.bp.pdf)
[pig.full.histgrowth.node.pdf](https://github.com/marschall-lab/panacus/files/13543822/pig.full.histgrowth.node.pdf)
[pig.full.histgrowth.node.txt](https://github.com/marschall-lab/panacus/files/13543844/pig.full.histgrowth.node.txt)

**Comment by ld9866** [comment]
The code is similar to your suggestion
grep -e '^W' pig.full.gfa | cut -f2-6 | awk '{ print $1 "#" $2 "#" $3 ":" $4 "-" $5 }' >> pig.full.paths.txt

#
grep -ive 'Sscrofa' pig.full.paths.txt > pig.full.paths.haplotypes.txt

RUST_LOG=info panacus histgrowth -t 16 -q 0,1,0.5,0.1 -S -s pig.full.paths.haplotypes.txt pig.full.gfa > pig.full.histgrowth.node.txt

panacus-visualize pig.full.histgrowth.node.txt >  pig.full.histgrowth.node.pdf

#
grep -ie 'Sscrofa' pig.full.paths.txt > pig.full.paths.Sscrofa.txt

RUST_LOG=info panacus histgrowth -t 16 -c bp -q 0,1,0.5,0.1 -e pig.full.paths.Sscrofa.txt -S -s pig.full.paths.haplotypes.txt pig.full.gfa > pig.full.histgrowth.noref.bp.txt

panacus-visualize pig.full.histgrowth.noref.bp.txt >  pig.full.histgrowth.noref.bp.pdf

**Comment by ld9866** [comment]
[pig.old.full.histgrowth.node.pdf](https://github.com/marschall-lab/panacus/files/13543926/pig.old.full.histgrowth.node.pdf)

This is our previous code result which is well.

**Comment by danydoerr** [comment]
> Again, the plots and tables look just fine, except for `pig.full.histgrowth.noref.bp.pdf` where I expected less amount of sequence, since it shouldn't include the reference. I suspect that here the issue is the same as with the HPRC data set, i.e., the file with the reference paths is empty. Is this also your concern, or is there something else that you do not find plausible with the results?

Ah scratch that. I also can't find any fault in `pig.full.histgrowth.noref.bp.pdf`, the amount of sequence shown seems to be much smaller than the total genome length, so it looks good to me. If you want to discuss the plot in. more detail, let's do this via mail (daniel.doerr@hhu.de)

**Comment by ld9866** [comment]
Dear developer:
The problem is "produce a plot quantifying the non-reference sequence of the graph", 
The problem we have now is that we are having some problems drawing non-reference sequences, and the results don't look very good, how do we solve this?

**Comment by ld9866** [comment]
However, I found that the non-reference sequence would reach 1.5Gb, which I think is unlikely, logically at 300Mb

**Comment by danydoerr** [comment]
> I uploaded our pig data, could you please help us see what is wrong with it.

Yes, that's what I am trying to do, but the data that you provide is not sufficient to see where the issue is. Can you please also provide the file paths file to me?

```shell
grep '^P' pig.full.gfa | cut -f2 > pig.full.paths.txt
grep -e '^W' pig.full.gfa | cut -f2-6 | awk '{ print $1 "#" $2 "#" $3 ":" $4 "-" $5 }' >> pig.full.paths.txt
```

> code: grep -ie 'Sscrofa' pig.full.paths.txt > pig.full.paths.Sscrofa.txt RUST_LOG=info panacus histgrowth -t 16 -c bp -q 0,1,0.5,0.1 -e pig.full.paths.Sscrofa.txt -S -s pig.full.paths.haplotypes.txt pig.full.gfa > pig.full.histgrowth.noref.bp.txt panacus-visualize pig.full.histgrowth.noref.bp.txt > pig.full.histgrowth.noref.bp.pdf
> 
> [pig.full.histgrowth.ref.bp.pdf](https://github.com/marschall-lab/panacus/files/13545382/pig.full.histgrowth.ref.bp.pdf) [pig.full.histgrowth.ref.bp.txt](https://github.com/marschall-lab/panacus/files/13545354/pig.full.histgrowth.ref.bp.txt)

The file names of your upload do not agree with the command that you typed.

**Comment by ld9866** [comment]
Here, l upload the result name is not mistake,is changed by myself to let you easily understand.
[pig.full.paths.txt](https://github.com/marschall-lab/panacus/files/13545652/pig.full.paths.txt)

**Comment by ld9866** [comment]
We were delighted to hear that the data was fine, and actually what we wanted to do was to make a graph of generic sequence growth, so that it would be a better illustration of our pan-genome being more representative. Now we are using the GFA result of Minigraph-cactus as input, how can we do that? As you said above, the node count is correct. The question now is how to get a visual result right.

**Comment by danydoerr** [comment]
> The question now is how to get a visual result right.

What's wrong with the visualization?
