### ISSUE TITLE
Request software updates

### ISSUE THREAD

**Issue by Xuelei-Dai** [marschall-lab/panacus#15]
Hello Daniel，

I found that the version of the `panacus` is no longer compatible with the results of Mingraph-Cactus (MC), and the final visualized graph is incorrect. I think this problem needs to be completely solved. It is necessary to use the current Mingraph-Cactus pipeline to construct the pan-genome and use the final results for visualization.

Best wishes
Xuelei

**Comment by danydoerr** [comment]
Thanks for reporting! Can you provide a graph where I can debug the issue?

**Comment by glennhickey** [comment]
I don't have any ideas of mc changes that would affect Panacus.  Here's two [yeast](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/examples/yeastPangenome.txt) graphs made with Cactus [v2.6.4](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.6.4) (which was used for the v1.1 HPRC graphs) and Cactus [v2.7.0](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.7.0) (which is the current release).

If there's a regression, I would think it would show up between these two graphs. 

http://public.gi.ucsc.edu/~hickey/debug/panacus/

**Comment by danydoerr** [comment]
Thanks @glennhickey!

**Comment by danydoerr** [comment]
Panacus runs smoothly on these graphs (see attached files). @Xuelei-Dai could you describe the specific issue in more detail and provide a graph that does not work with the current release of panacus? 

[yeast-v2.6.4.histgrowth.all.html.gz](https://github.com/marschall-lab/panacus/files/13615705/yeast-v2.6.4.histgrowth.all.html.gz)
[yeast-v2.6.4.histgrowth.all.html.log.gz](https://github.com/marschall-lab/panacus/files/13615706/yeast-v2.6.4.histgrowth.all.html.log.gz)
[yeast-v2.6.4.histgrowth.all.pdf](https://github.com/marschall-lab/panacus/files/13615707/yeast-v2.6.4.histgrowth.all.pdf)
[yeast-v2.6.4.histgrowth.all.tsv.gz](https://github.com/marschall-lab/panacus/files/13615708/yeast-v2.6.4.histgrowth.all.tsv.gz)
[yeast-v2.6.4.histgrowth.all.tsv.log.gz](https://github.com/marschall-lab/panacus/files/13615709/yeast-v2.6.4.histgrowth.all.tsv.log.gz)
[yeast-v2.7.0.histgrowth.all.html.gz](https://github.com/marschall-lab/panacus/files/13615710/yeast-v2.7.0.histgrowth.all.html.gz)
[yeast-v2.7.0.histgrowth.all.html.log.gz](https://github.com/marschall-lab/panacus/files/13615711/yeast-v2.7.0.histgrowth.all.html.log.gz)
[yeast-v2.7.0.histgrowth.all.pdf](https://github.com/marschall-lab/panacus/files/13615712/yeast-v2.7.0.histgrowth.all.pdf)
[yeast-v2.7.0.histgrowth.all.tsv.gz](https://github.com/marschall-lab/panacus/files/13615713/yeast-v2.7.0.histgrowth.all.tsv.gz)
[yeast-v2.7.0.histgrowth.all.tsv.log.gz](https://github.com/marschall-lab/panacus/files/13615714/yeast-v2.7.0.histgrowth.all.tsv.log.gz)

**Comment by Xuelei-Dai** [comment]
Thanks @danydoerr and @glennhickey!

In the current version of [Mingraph-Cactus (MC)](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.6.4), the gfa file does not have `P` line, and the new `W` line was changed. Since I referred to the [`Pangenome Coverage and Growth Statistics`](https://github.com/marschall-lab/panacus#pangenome-coverage-and-growth-statistics) pipeline  (convert the 1.1 version of `gfa` to 1.0 (`vg convert -gfW`)), recently I directly used the 1.1 version of the `gfa `file as the input of `panacus`, it's okay. So I suggest that you can add some instructions to your pipeline, for example, how should the `gfa `1.1 version be run?

Best,
Xuelei

**Comment by danydoerr** [comment]
That's a good point, @Xuelei-Dai, the current README does not contain an example for the MC graph. I have now added an example for the [MC graph](https://github.com/marschall-lab/panacus#minigraph-cactus).

To be perfectly clear, `panacus` has always supported GFA 1.1 and therefore also the latest MC graphs. Neither any update is required, nor any bug to be fixed. The example in the README suggests to visualize pangenome growth only for a subset of samples (those corresponding to haplotypes). This preprocessing is not part of `panacus` and remains the responsibility of the users.
