### ISSUE TITLE
A problem while running panacus-visualize

### ISSUE THREAD

**Issue by syresbr** [marschall-lab/panacus#17]
I was trying to run panacus-visualize with my data but it gave me this error 
``Traceback (most recent call last):
  File "/home/gustavo/panacus-0.2.3_linux_x86_64/bin/panacus-visualize", line 16, in <module> from matplotlib.transforms import Bbox ModuleNotFoundError: No module named 'matplotlib'``

and in the file is this code `from matplotlib.transforms import Bbox`
And I tried to run it with your example and it got the same error.

Thanks for your time.

**Comment by danydoerr** [comment]
Thanks for reporting, Gustavo!

I assume you downloaded the binary release. If you install panacus with conda, all required python packages are installed, too. In case of the binary, python dependencies are not resolved -- you must handle these yourself. You can find the list of dependencies in the README (https://github.com/marschall-lab/panacus)
