### ISSUE TITLE
Haplotype labels in TSV, visualisations ?

### ISSUE THREAD

**Issue by blinard-BIOINFO** [marschall-lab/panacus#20]
Hello,
Great tool. 
Is it possible to display the haplotypes labels from GFA P-lines or W-lines into the TSV outputs, as well as the HTML/PDF outputs ?

I tried with different GFA files, containing either P-lines or W-lines.
However, the output always lists the haplotypes on X axes with integers from 1 to n.

If this is not implemented, does the enumeration corresponds to the order of the lines in the GFA ? or from the haplotype.txt files ?

Thanks

**Comment by blinard-BIOINFO** [comment]
Thanks you for your fast reply.
I also tried with ordering, however I think I miss the documentation to understand how to make any outputs reusing the P-lines or W-lines.

For instance, below is my haplotype list: 

```
# content of myexp.paths.haplotypes.txt

CH_320_5#0#Chr1__CH_320_5:0-49187872
KR_091_H1#0#Chr1__KR_091_H1:0-47283768
KR_091_H2#0#Chr1__KR_091_H2:0-43236572
KZ_150_8_H1#0#Chr1__KZ_150_8_H1:0-47660619
KZ_150_8_H2#0#Chr1__KZ_150_8_H2:0-51744517
Marouch_v3p1#0#Chr1_Marouch_v3p1:0-44417728
RRxCH240_1_plA_H2#0#Chr1_RRxCH240_1_plA_H2:0-45594464
RRxCH240_1_plB_H2#0#Chr1_RRxCH240_1_plB_H2:0-46275222
Rojo_HORA#0#Chr1_Rojo_HORA:0-45121954
RougeRoussillon_H1#0#Chr1_RougeRoussillon_H1:0-49875448
RougeRoussillon_H2#0#Chr1_RougeRoussillon_H2:0-48193998
Stella_v1p1#0#Chr1__Stella_v1p1:0-43521413
Sungold#0#Chr1__Sungold:0-44445119
```

The same labels are present in the GFA file.

```
# grep -e "^P" mytest.gfa | cut -f1,2
P	Sungold#0#Chr1__Sungold#0
P	Stella_v1p1#0#Chr1__Stella_v1p1#0
P	RougeRoussillon_H2#0#Chr1_RougeRoussillon_H2#0
P	RougeRoussillon_H1#0#Chr1_RougeRoussillon_H1#0
P	Rojo_HORA#0#Chr1_Rojo_HORA#0
P	Rojo_HCUR#0#Chr1_Rojo_HCUR#0
P	RRxCH240_1_plB_H2#0#Chr1_RRxCH240_1_plB_H2#0
P	RRxCH240_1_plA_H2#0#Chr1_RRxCH240_1_plA_H2#0
P	Marouch_v3p1#0#Chr1_Marouch_v3p1#0
P	KZ_150_8_H2#0#Chr1__KZ_150_8_H2#0
P	KZ_150_8_H1#0#Chr1__KZ_150_8_H1#0
P	KR_091_H2#0#Chr1__KR_091_H2#0
P	KR_091_H1#0#Chr1__KR_091_H1#0
P	CH_320_5#0#Chr1__CH_320_5#0
```

However, whatever I try, the output CSV or plots only show 1, 2, 3, ... labels for the haplotypes. It never shows the labels.
Then, I'm not sure where haplotype corresponds to 4, which one to 7, ...etc...

![Capture d’écran du 2024-04-04 12-00-45](https://github.com/marschall-lab/panacus/assets/22132778/9c56780c-244d-46a1-bcd0-1a2041097f5b)

**Comment by lucaparmigiani** [comment]
Hi, Benjamin,

I have the impression the meaning of the histogram might not be what you think. 
Let me see if I am getting your point right.

The histogram **does not** show how many bps appear in haplotype 1, how many in haplotype 2, and so on.

Each bar in the histogram represents the following:
- first bar: how many bps appear **only in a single haplotype** (this can be haplotype 1 or haplotype 2,or ... haplotype n, as long as they appear only once), 
- second bar: how many bps appear in two haplotypes (for example appearing in haplotype 1 and haplotype 4 **but in no other haplotype**) 
- ...
- nth bar: how many bps appear in **all haplotypes** (also refered to as core).

What you would like, if I am understanding correctly, is to know "how many bps appear in haplotype 1 (eg, Sungold#0#Chr1__Sungold#0), how many bps appear in haplotype 2 (eg, Stella_v1p1#0#Chr1__Stella_v1p1#0) and so on. Is it correct?

**Comment by blinard-BIOINFO** [comment]
Thank you for your explanation.

But then how did you obtain the graph which is at the bottom of the readme of this github.

![hprc-v1 0-mc-grch38 ordered-histgrowth bp](https://github.com/marschall-lab/panacus/assets/22132778/e14855c6-907e-4f37-8d3f-7be33ed91143)

I may be confused, but as I understand it this is the graph growth, haplotype after haplotype, because haplotype labels are on the X axis. 

I wanted to reproduce this graph.
But whatever command I try (`ordered-histgrowth`, `histgrowth`...), I never get haplotype labels on the figure.


I initially followed the README tutorial, and when I follow the commands on the README, I do not manage to get these labels.

In the README, you have this line:
```
echo 'HG03492 HG00438 HG00621 HG00673 HG02080 HG00733 HG00735 HG00741 HG01071 HG01106 HG01109 HG01123 HG01175 HG01243 HG01258 HG01358 HG01361 HG01928
HG01952 HG01978 HG02148 HG01891 HG02055 HG02109 HG02145 HG02257 HG02486 HG02559 HG02572 HG02622 HG02630 HG02717 HG02723 HG02818 HG02886 HG03098
HG03453 HG03486 HG03516 HG03540 HG03579 NA18906 NA20129 NA21309' | tr ' ' '\n' > hprc-v1.0-mc-grch38.order.samples.txt
```

which generates `hprc-v1.0-mc-grch38.order.samples.txt`


However, this file is not used in any of the commands of the README.
I expected this to be a mistake and used this file for the ordering, and my issue started there.

**Comment by danydoerr** [comment]
@blinard-BIOINFO thanks for pointing this out, this is indeed a bug in the documentation. The correct command should be

`RUST_LOG=info panacus ordered-histgrowth -c bp -O hprc-v1.0-mc-grch38.order.samples.txt -t4 -l 1,2,3,42 -S -e hprc-v1.0-mc-grch38.paths.grch38.txt hprc-v1.0-mc-grch38.gfa > hprc-v1.0-mc-grch38.ordered-histgrowth.bp.tsv`

I'm running the example now again to see whether it produces the intended output.

**Comment by danydoerr** [comment]
@blinard-BIOINFO:  @heringerp fixed the issue.
