### ISSUE TITLE
macOS binary missing

### ISSUE THREAD

**Issue by pdoris** [marschall-lab/panacus#27]
wget --no-check-certificate -c https://github.com/marschall-lab/panacus/releases/download/0.2.3/panacus-0.2.3_macos_arm64.tar.gz
--2024-06-20 08:19:21--  https://github.com/marschall-lab/panacus/releases/download/0.2.3/panacus-0.2.3_macos_arm64.tar.gz
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-06-20 08:19:21 ERROR 404: Not Found.

**Comment by heringerp** [comment]
I think there is a typo in the URL you used: should be [https://github.com/marschall-lab/panacus/releases/download/0.2.3/panacus-0.2.3_macos_x_arm64.tar.gz](url) (macos_x_arm64 instead of macos_arm64)

**Comment by danydoerr** [comment]
Dear @pdoris, thanks for the notice. I fixed the issue now-- you should be able to download the binary under the original link.
