### ISSUE TITLE
What does the output content represent

### ISSUE THREAD

**Issue by xuxingyubio** [marschall-lab/panacus#3]
When I used the pangenome-growth command, I got a 5-column data, and what do the last three columns represent?When I build a sample file, I only need to write the sample name instead of using the haplotype form of sample name. 1.2. Is this a requirement for the sample file that was previously constructed as a pangenome?

**Comment by danydoerr** [comment]
Please use use the "ng" branch. It will be pushed to many any day now. I will also add a tutorial and documentation to the README. For now, please use https://hackmd.io/asojhSf-T8GOJOr9HQj_IA#Panacus for orientation. Since the file format changed a lot in this new version, I think your question will no longer be valid.  If you have any questions, please post here.

**Comment by 1538501175** [comment]
How can I download Panacus? I couldn't find a download link on your latest webpage https://hackmd.io/asojhSf-T8GOJOr9HQj_IA#Panacus

**Comment by 1538501175** [comment]
Sorry to bother you again. I don't understand what the "ng" branch means. I was able to install pangenome-growth0.1 using the recommended command "cargo build --release" and successfully run it on animals pangenome. In your tutorial notes, you mentioned that it's already available on the course workstations, but I don't have access to those workstations.

**Comment by danydoerr** [comment]
﻿Sure, I’m happy to help! Just do `git branch ng && git pull origin ng` you will be on the ng branch. Then recompile and you’re good to go. Note that panacea supports only Linux for now, but with the planned release it will also support MacOS. On 17. May 2023, at 15:18, jinster ***@***.***> wrote:﻿
Sorry to bother you again. I don't understand what the "ng" branch means. I was able to install pangenome-growth0.1 using the recommended command "cargo build --release" and successfully run it on animals pangenome. In your tutorial notes, you mentioned that it's already available on the course workstations, but I don't have access to those workstations.

**Comment by danydoerr** [comment]
Sorry, it's `git checkout ng && git pull origin ng`.

**Comment by danydoerr** [comment]
New version is now in `main` and finally released (including pre-compiled executables). I'm closing this issue now.
