### ISSUE TITLE
coverage/quorum

### ISSUE THREAD

**Issue by jwli-code** [marschall-lab/panacus#30]
I would like to know what the coverage/quorum parameter means.  
`histgrowth -t4 -l 1,2,1,1,1 -q 0,0,1,0.5,0.1`

**Comment by danydoerr** [comment]
@jwli-code thanks for the request--I really need to revise the README page. 

In the meantime, you can find a description here https://hackmd.io/asojhSf-T8GOJOr9HQj_IA#Panacus

Let me know if this is sufficient to answer your question.

**Comment by danydoerr** [comment]
the README now contains a section that describes these parameters
