### ISSUE TITLE
what dose coverage and quorum mean？

### ISSUE THREAD

**Issue by peanut-nu** [marschall-lab/panacus#31]
hi, I'm sorry to bother you.But i really don't konw what dose coverage and quorum mean.Can you help me ?And can you help me see what's wrong with my results and how they can be interpreted? Again, my apologies.
![image](https://github.com/user-attachments/assets/952f200e-d4fe-4f62-8b85-b30e428a0d34)
![image](https://github.com/user-attachments/assets/35708ead-fdf1-4c2b-a1c7-5885125eacf7)
![image](https://github.com/user-attachments/assets/7c0b5de0-3cb5-4537-a396-e66ba1c87a67)
![image](https://github.com/user-attachments/assets/d2762409-fb0d-4c86-9869-a457b6f2196c)
![image](https://github.com/user-attachments/assets/d53210f4-f30c-4969-a89e-c77e3436ac8e)
![image](https://github.com/user-attachments/assets/76771edb-863b-4098-b4a1-4fdef6afc534)

**Comment by danydoerr** [comment]
Hey @peanut-nu, sure no apologies needed, I'm happy to help. I don't think there's anything wrong with your results. Regarding the coverage and quorum parameters:

- coverage lets you calculate the growth statistic for the subset of countables (bps/nodes/edges) that are shared by a minimum number of haplotypes/samples. In other words, Panacus will only take those bars of the coverage histogram (the three last plots that you posted) into account when calculating pangenome growth that satisfy the threshold
- quorum: This parameter allows you to control the minimum number of shared countables when a new haplotype/sample is "added" to the pangenome (progression along the x-axis). For instance, if you set the quorum to 100%, then this means that only those countables in are counted in the newly added genome that are already part of the pangenome. That way you can measure what is known as pangenome core. If you modulate the threshold, you can calculate e.g. soft core (90%), or be a bit more strict on pangenome growth (e.g. 10%, which means that each countable of the new genome must be shared by at least 10% of the already contained genomes). 

You have very few samples/haplotypes, and thus the edge effects of the quorum threshold is particularly pronounced. 

Hope this helps!

**Comment by peanut-nu** [comment]
> Hey @peanut-nu, sure no apologies needed, I'm happy to help. I don't think there's anything wrong with your results. Regarding the coverage and quorum parameters:
> 
> * coverage lets you calculate the growth statistic for the subset of countables (bps/nodes/edges) that are shared by a minimum number of haplotypes/samples. In other words, Panacus will only take those bars of the coverage histogram (the three last plots that you posted) into account when calculating pangenome growth that satisfy the threshold
> * quorum: This parameter allows you to control the minimum number of shared countables when a new haplotype/sample is "added" to the pangenome (progression along the x-axis). For instance, if you set the quorum to 100%, then this means that only those countables in are counted in the newly added genome that are already part of the pangenome. That way you can measure what is known as pangenome core. If you modulate the threshold, you can calculate e.g. soft core (90%), or be a bit more strict on pangenome growth (e.g. 10%, which means that each countable of the new genome must be shared by at least 10% of the already contained genomes).
> 
> You have very few samples/haplotypes, and thus the edge effects of the quorum threshold is particularly pronounced.
> 
> Hope this helps!

 You've explained it very well, I'll look into it a bit more carefully, thanks a lot really!Hope you have a nice day !

**Comment by danydoerr** [comment]
Thanks, you too!
