### ISSUE TITLE
Validity of results

### ISSUE THREAD

**Issue by aaaniich** [marschall-lab/panacus#32]
Good afternoon!
I'm sorry to bother you.
Could you please advise me what could supposedly be wrong with my results?
I saw a thread above with a similar case. 
But I'm confused by the fact that my results are so different between bp and edges. Could this be due to the fact that I didn't use any masking for the satellite sequence? 
![12_hap_hg38 gfa_growth_edge (2)](https://github.com/user-attachments/assets/0f608d07-a197-4f18-8669-bf4b298668e4)
![12_hap_hg38 gfa_growth_node (1)](https://github.com/user-attachments/assets/8f0603fe-fe3f-4141-8a3b-321cc2861a84)
![12_hap_hg38 gfa_growth_bp (1)](https://github.com/user-attachments/assets/228010d8-186e-46ee-874a-560f13d18ce0)

**Comment by aaaniich** [comment]
> Dear Anna, apologies for the late response--I have been on vacation. Edge and bp count have different properties, and that's why they also exhibit different growth curves. For Instance, it is expected that the core genome (coverage >= 1, quorum = 100%) of edges tends converges towards 0, as edges that are shared between all genomes should not exist, unless in presence of segmental duplication.
> 
> From the figures alone, I cannot spot any obvious mistake of your analysis.

Thanks so much for the reply! This has helped me a lot. I was just looking at the HPRC example where the common part is preserved, even though they have a lot more genomes represented and I was worried.
Thank you for your work!

**Comment by danydoerr** [comment]
You're welcome. Feel free to post further questions if you have!
