### ISSUE TITLE
could you give us an example of cactus?

### ISSUE THREAD

**Issue by xuxingyubio** [marschall-lab/panacus#4]

**Comment by xuxingyubio** [comment]
Sorry to bother you, could you give me an example of cactus? I downloaded the pan genome constructed using cactus from HPRC, and it seems that there are some differences between it and pggb when using this software. As I have just come into contact with this field, I don't know how to solve it.

**Comment by xuxingyubio** [comment]
Thank you for your answer.
How to quantify the amount of  non-reference(GRCh38) sequence has always troubled me. 
Does the above step indicate this information, or does it require some processing of the constructed pangenome?

**Comment by danydoerr** [comment]
Fig. 3g is an ordered growth histogram (which you can also produce with this tool). But you can also do this by looking at all possible permutations, which is what `panacus histgrowth` does. If you follow the steps from above, you should be able to get the attached data / plot. As expected, the average 1st genome adds about 30Mb of non-reference sequence to the pangenome. The data is consistent with Fig. 3g from the paper.

[hprc-v1.0-mc-grch38.histgrowth.nogrch38.bp.pdf](https://github.com/marschall-lab/panacus/files/11533753/hprc-v1.0-mc-grch38.histgrowth.nogrch38.bp.pdf)
[hprc-v1.0-mc-grch38.histgrowth.nogrch38.bp.txt](https://github.com/marschall-lab/panacus/files/11533754/hprc-v1.0-mc-grch38.histgrowth.nogrch38.bp.txt)
