### ISSUE TITLE
error bar in the growth plot for #nodes

### ISSUE THREAD

**Issue by WenboLVCong** [marschall-lab/panacus#48]
Hi @danydoerr :)

I have a few questions about the growth plot for #nodes( the second pic in https://github.com/marschall-lab/panacus/blob/main/examples/pangenome_growth_minigraph_cactus.md ). is the X-axis the sample number? is the pink bar the nodes covered by all these count of sample? for example, say X-axis =20, does it mean randomly pick 20 samples from the total samples (i.e. 46)? so the Y-axis of pink bar means the mean of #nodes covered by these 20 samples sets? because there are many samples sets if randomly pick 20 samples from 46 samples. SO my concern is :  Can this plot show the error bar for these sampling? 

Thank you in advance!
Best regards,
Wenbo

**Comment by danydoerr** [comment]
Hi @WenboLVCong ,

Yes, the X-Axis of the coverage histogram and the pangenome growth plots are samples. The coverage histogram shows how many nodes (panacus can generate a corresponding plot also for basepairs) are covered by _exactly_ 20 out of the 46 genomes. 
Pancus does not do sampling, but it calculates the coverage histogram and the pangenome growth with an exact formula. So there is no need for error bars.

**Comment by WenboLVCong** [comment]
> Hi @danydoerr :)

Thank you very much for reply. I just read the paper https://www.biorxiv.org/content/10.1101/2024.06.11.598418v1.full.pdf. but still can not get it. Say X-axis=20, if Panacus does not do sampling, so which 20 samples out of the 46 samples are used for counting? Or does it mean: among the 46 samples, the nodes covered by exactly 20 samples? If so, sum all the histogram (X-axis from 1 to 46) up, should equal to the size of the whole pangeome?

Thank you very much!
Wenbo

**Comment by danydoerr** [comment]
Yes, it's exactly as you describe. Summing over the node coverage histogram gives you the total number of nodes in the graph.

**Comment by WenboLVCong** [comment]
I mean the histogram in the second pic (i.e.  growth plot for #nodes), not the first pic. take my result as example. 
![image](https://github.com/user-attachments/assets/76433084-4221-4010-a4bb-6199b6c24f82)
the total size of the pangenome is about 303mb, equal to the y-axis of pink bar when x-axis=16. if sum all these bars together, it is much bigger than 303mb. I thought it was not the size of pangenome. 
the size of a single genome is ~ 220 mb

**Comment by danydoerr** [comment]
So, for the pangenome growth plot for bps, the last bar should be exactly the total number bps in your pangenome

**Comment by WenboLVCong** [comment]
yes , I set quorum >=0. I was wondering, for the second bar (x-axis = 2), how to get the y-axis of pink bar. if with sampling, which two samples were used to count the bps?

**Comment by WenboLVCong** [comment]
yes , I set quorum >=0. I was wondering, for the second bar (x-axis = 2), how to get the y-axis of pink bar. if without sampling, which two samples were used to count the bps?

**Comment by heringerp** [comment]
Hi Wenbo,

so the way Panacus works is that it does not look at specific samples, but instead at all of them. So for the second bar (x=2) it will look at all the nodes. It then finds out in how many combinations that node appears at least once. For a node that appears in 4 of the 6 paths (this fact is contained in the coverage histogram) this calculation would look like this:

1. there are in this case ${16 \choose 2}$ possibilities of drawing samples
2. in ${16 - 4 \choose 2}$ combinations the node does not appear
3. so it appears at least once in ${16 \choose 2} - {16 - 4 \choose 2}$ combinations
4. this gives us a probability for the node to appear of $\frac{{16 \choose 2} - {16 - 4 \choose 2}}{{16 \choose 2}}$

We then sum over all the probabilities for all the nodes to get the height of the bar.

**Comment by WenboLVCong** [comment]
Hi Peter,

Thank you very much! I got it finally !

Best regards,
Wenbo
