### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by johanneskoester** [marschall-lab/panacus#5]
Nowadays, conda should be replaced by mamba, which is much faster and also solves dependencies in a more optimal way. Further, the bioconda channel always should be combined with  the conda-forge channel because it is build against that instead of the defaults channel. Something like `mamba install -c conda-forge -c bioconda panacus`. For getting a mamba installation you can refer to the mambaforge distribution.

**Comment by danydoerr** [comment]
Thanks! I was indeed quite torn about whether referring to conda or mamba for installation, because, as you say it is *so much* better, but at the same time worried that I'd introduce another unnecessary dependency. Thanks for the encouragement and the helpful advice!

**Comment by danydoerr** [comment]
README.md is now updated.
