### ISSUE TITLE
path coordinates

### ISSUE THREAD

**Issue by baozg** [marschall-lab/panacus#8]
Hi, 

How could I provide path coordinates for `panacus` from `pggb` graph? Since it didn't have an interval in the GFA, this function only works for `Minigraph-Cactus` graph?

**Comment by danydoerr** [comment]
`panacus` does not make use of node annotations, if that is what you mean. It uses the sequence underlying the nodes as reference for the coordinates. In other words, path coordinates should work in `pggb` as well as `Minigraph-Cactus`, and I have tested it on both. Does it not work for you?

**Comment by baozg** [comment]
No. It did work with my pggb graph. Here is the command I use:

```bash
panacus hist -c bp -e Col-0.CEN.bed -H -t 12 ../At_Chr1_p90_s10000/panCEN.Chr1.fa.gz.f6e6337.f85392c.20baff7.smooth.final.gfa > Chr1.hist
```

And here is the bed info
```bash
Col-0#Chr1      14842915        17129565
Col-0#Chr2      5281568 5281745
Col-0#Chr3      13596521        15747999
Col-0#Chr4      5256168 5256346
Col-0#Chr5      12395998        14812445
```

**Comment by danydoerr** [comment]
Can you send me the graph, too?

**Comment by baozg** [comment]
The graph is quite large, could I send you a link by email?

**Comment by danydoerr** [comment]
Yes--Just sent you an email, so you have mine.

**Comment by baozg** [comment]
Thanks! Sent it. By the way, what's the exact meaning of quorum?

**Comment by danydoerr** [comment]
Quorum sets the number of paths/groups that must share the counted graph feature when going from n to n+1. The simplest way to understand quorum when it is set to 100%, i.e, `-q 1`. In that case, `panacus` would count only those graph features that are shared by _all_ paths/groups. This is commonly known as `core` genome. Setting `-q 0.5` is also known as shell pangenome and `-q 0.1` cloud pangenome. Here are some more explanations: https://hackmd.io/asojhSf-T8GOJOr9HQj_IA#Panacus

**Comment by baozg** [comment]
Actually, `panacus` run successfully with BED. The error is because I use whole genome bed for chr1 graph.
